# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ICPS.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ICPS.proto',
  package='freerds.icps',
  serialized_pb='\n\nICPS.proto\x12\x0c\x66reerds.icps\"E\n\x12VersionInfoRequest\x12\x11\n\tsessionId\x18\x01 \x02(\r\x12\r\n\x05major\x18\x02 \x02(\r\x12\r\n\x05minor\x18\x03 \x02(\r\"3\n\x13VersionInfoResponse\x12\r\n\x05major\x18\x02 \x02(\r\x12\r\n\x05minor\x18\x03 \x02(\r\"`\n\x17\x41uthenticateUserRequest\x12\x11\n\tsessionId\x18\x01 \x02(\r\x12\x10\n\x08username\x18\x02 \x02(\t\x12\x10\n\x08password\x18\x03 \x02(\t\x12\x0e\n\x06\x64omain\x18\x04 \x02(\t\"\xb9\x01\n\x18\x41uthenticateUserResponse\x12\x46\n\nauthStatus\x18\x01 \x02(\x0e\x32\x32.freerds.icps.AuthenticateUserResponse.AUTH_STATUS\x12\x17\n\x0fserviceEndpoint\x18\x02 \x01(\t\"<\n\x0b\x41UTH_STATUS\x12\x14\n\x10\x41UTH_SUCCESSFULL\x10\x00\x12\x17\n\x13\x41UTH_BAD_CREDENTIAL\x10\x01\"&\n\x11\x45ndSessionRequest\x12\x11\n\tsessionId\x18\x01 \x02(\r\"%\n\x12\x45ndSessionResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08*C\n\x07MSGTYPE\x12\x15\n\x10\x41uthenticateUser\x10\xc8\x01\x12\x0f\n\nEndSession\x10\xc9\x01\x12\x10\n\x0bVersionInfo\x10\xca\x01')

_MSGTYPE = _descriptor.EnumDescriptor(
  name='MSGTYPE',
  full_name='freerds.icps.MSGTYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AuthenticateUser', index=0, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EndSession', index=1, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VersionInfo', index=2, number=202,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=517,
  serialized_end=584,
)

MSGTYPE = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
AuthenticateUser = 200
EndSession = 201
VersionInfo = 202


_AUTHENTICATEUSERRESPONSE_AUTH_STATUS = _descriptor.EnumDescriptor(
  name='AUTH_STATUS',
  full_name='freerds.icps.AuthenticateUserResponse.AUTH_STATUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTH_SUCCESSFULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTH_BAD_CREDENTIAL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=376,
  serialized_end=436,
)


_VERSIONINFOREQUEST = _descriptor.Descriptor(
  name='VersionInfoRequest',
  full_name='freerds.icps.VersionInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='freerds.icps.VersionInfoRequest.sessionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='major', full_name='freerds.icps.VersionInfoRequest.major', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='freerds.icps.VersionInfoRequest.minor', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=97,
)


_VERSIONINFORESPONSE = _descriptor.Descriptor(
  name='VersionInfoResponse',
  full_name='freerds.icps.VersionInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='freerds.icps.VersionInfoResponse.major', index=0,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='freerds.icps.VersionInfoResponse.minor', index=1,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=99,
  serialized_end=150,
)


_AUTHENTICATEUSERREQUEST = _descriptor.Descriptor(
  name='AuthenticateUserRequest',
  full_name='freerds.icps.AuthenticateUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='freerds.icps.AuthenticateUserRequest.sessionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='freerds.icps.AuthenticateUserRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='freerds.icps.AuthenticateUserRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='freerds.icps.AuthenticateUserRequest.domain', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=248,
)


_AUTHENTICATEUSERRESPONSE = _descriptor.Descriptor(
  name='AuthenticateUserResponse',
  full_name='freerds.icps.AuthenticateUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authStatus', full_name='freerds.icps.AuthenticateUserResponse.authStatus', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceEndpoint', full_name='freerds.icps.AuthenticateUserResponse.serviceEndpoint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUTHENTICATEUSERRESPONSE_AUTH_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=251,
  serialized_end=436,
)


_ENDSESSIONREQUEST = _descriptor.Descriptor(
  name='EndSessionRequest',
  full_name='freerds.icps.EndSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='freerds.icps.EndSessionRequest.sessionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=438,
  serialized_end=476,
)


_ENDSESSIONRESPONSE = _descriptor.Descriptor(
  name='EndSessionResponse',
  full_name='freerds.icps.EndSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='freerds.icps.EndSessionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=478,
  serialized_end=515,
)

_AUTHENTICATEUSERRESPONSE.fields_by_name['authStatus'].enum_type = _AUTHENTICATEUSERRESPONSE_AUTH_STATUS
_AUTHENTICATEUSERRESPONSE_AUTH_STATUS.containing_type = _AUTHENTICATEUSERRESPONSE;
DESCRIPTOR.message_types_by_name['VersionInfoRequest'] = _VERSIONINFOREQUEST
DESCRIPTOR.message_types_by_name['VersionInfoResponse'] = _VERSIONINFORESPONSE
DESCRIPTOR.message_types_by_name['AuthenticateUserRequest'] = _AUTHENTICATEUSERREQUEST
DESCRIPTOR.message_types_by_name['AuthenticateUserResponse'] = _AUTHENTICATEUSERRESPONSE
DESCRIPTOR.message_types_by_name['EndSessionRequest'] = _ENDSESSIONREQUEST
DESCRIPTOR.message_types_by_name['EndSessionResponse'] = _ENDSESSIONRESPONSE

class VersionInfoRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSIONINFOREQUEST

  # @@protoc_insertion_point(class_scope:freerds.icps.VersionInfoRequest)

class VersionInfoResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSIONINFORESPONSE

  # @@protoc_insertion_point(class_scope:freerds.icps.VersionInfoResponse)

class AuthenticateUserRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHENTICATEUSERREQUEST

  # @@protoc_insertion_point(class_scope:freerds.icps.AuthenticateUserRequest)

class AuthenticateUserResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHENTICATEUSERRESPONSE

  # @@protoc_insertion_point(class_scope:freerds.icps.AuthenticateUserResponse)

class EndSessionRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENDSESSIONREQUEST

  # @@protoc_insertion_point(class_scope:freerds.icps.EndSessionRequest)

class EndSessionResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENDSESSIONRESPONSE

  # @@protoc_insertion_point(class_scope:freerds.icps.EndSessionResponse)


# @@protoc_insertion_point(module_scope)
