# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbRPC.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pbRPC.proto',
  package='freerds.pbrpc',
  serialized_pb='\n\x0bpbRPC.proto\x12\rfreerds.pbrpc\"+\n\x0bVersionInfo\x12\r\n\x05major\x18\x01 \x02(\r\x12\r\n\x05minor\x18\x02 \x02(\r\"\x8d\x02\n\x07RPCBase\x12\x0b\n\x03tag\x18\x01 \x02(\r\x12\x19\n\nisResponse\x18\x02 \x02(\x08:\x05\x66\x61lse\x12\x39\n\x06status\x18\x03 \x02(\x0e\x32 .freerds.pbrpc.RPCBase.RPCSTATUS:\x07SUCCESS\x12\x0f\n\x07msgType\x18\x04 \x02(\r\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x18\n\x10\x65rrorDescription\x18\x06 \x01(\t\x12/\n\x0bversionInfo\x18\x07 \x01(\x0b\x32\x1a.freerds.pbrpc.VersionInfo\"2\n\tRPCSTATUS\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0c\n\x08NOTFOUND\x10\x02')



_RPCBASE_RPCSTATUS = _descriptor.EnumDescriptor(
  name='RPCSTATUS',
  full_name='freerds.pbrpc.RPCBase.RPCSTATUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTFOUND', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=295,
  serialized_end=345,
)


_VERSIONINFO = _descriptor.Descriptor(
  name='VersionInfo',
  full_name='freerds.pbrpc.VersionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='freerds.pbrpc.VersionInfo.major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='freerds.pbrpc.VersionInfo.minor', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=73,
)


_RPCBASE = _descriptor.Descriptor(
  name='RPCBase',
  full_name='freerds.pbrpc.RPCBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='freerds.pbrpc.RPCBase.tag', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isResponse', full_name='freerds.pbrpc.RPCBase.isResponse', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='freerds.pbrpc.RPCBase.status', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='freerds.pbrpc.RPCBase.msgType', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='freerds.pbrpc.RPCBase.payload', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorDescription', full_name='freerds.pbrpc.RPCBase.errorDescription', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='versionInfo', full_name='freerds.pbrpc.RPCBase.versionInfo', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RPCBASE_RPCSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=345,
)

_RPCBASE.fields_by_name['status'].enum_type = _RPCBASE_RPCSTATUS
_RPCBASE.fields_by_name['versionInfo'].message_type = _VERSIONINFO
_RPCBASE_RPCSTATUS.containing_type = _RPCBASE;
DESCRIPTOR.message_types_by_name['VersionInfo'] = _VERSIONINFO
DESCRIPTOR.message_types_by_name['RPCBase'] = _RPCBASE

class VersionInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSIONINFO

  # @@protoc_insertion_point(class_scope:freerds.pbrpc.VersionInfo)

class RPCBase(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCBASE

  # @@protoc_insertion_point(class_scope:freerds.pbrpc.RPCBase)


# @@protoc_insertion_point(module_scope)
