# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ICP.proto',
  package='freerds.icp',
  serialized_pb='\n\tICP.proto\x12\x0b\x66reerds.icp\".\n\x17IsChannelAllowedRequest\x12\x13\n\x0b\x43hannelName\x18\x01 \x02(\t\"2\n\x18IsChannelAllowedResponse\x12\x16\n\x0e\x43hannelAllowed\x18\x01 \x02(\x08\"\r\n\x0bPingRequest\"\x1c\n\x0cPingResponse\x12\x0c\n\x04pong\x18\x01 \x02(\x08\"4\n\x1c\x44isconnectUserSessionRequest\x12\x14\n\x0c\x43onnectionId\x18\x01 \x02(\r\"5\n\x1d\x44isconnectUserSessionResponse\x12\x14\n\x0c\x64isconnected\x18\x01 \x02(\x08\"0\n\x18LogOffUserSessionRequest\x12\x14\n\x0c\x43onnectionId\x18\x01 \x02(\r\".\n\x19LogOffUserSessionResponse\x12\x11\n\tloggedoff\x18\x01 \x02(\x08\"I\n\x1f\x46\x64sApiVirtualChannelOpenRequest\x12\x11\n\tSessionID\x18\x01 \x02(\r\x12\x13\n\x0bVirtualName\x18\x02 \x02(\t\"<\n FdsApiVirtualChannelOpenResponse\x12\x18\n\x10\x43onnectionString\x18\x01 \x02(\t\"\\\n\x10LogonUserRequest\x12\x14\n\x0c\x43onnectionId\x18\x01 \x02(\r\x12\x10\n\x08Username\x18\x02 \x02(\t\x12\x10\n\x08Password\x18\x03 \x02(\t\x12\x0e\n\x06\x44omain\x18\x04 \x02(\t\",\n\x11LogonUserResponse\x12\x17\n\x0fServiceEndpoint\x18\x01 \x02(\t\"@\n\x0fSwitchToRequest\x12\x14\n\x0c\x63onnectionId\x18\x01 \x02(\r\x12\x17\n\x0fserviceEndpoint\x18\x02 \x02(\t\"#\n\x10SwitchToResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08*\x96\x01\n\x07MSGTYPE\x12\x14\n\x10IsChannelAllowed\x10\x01\x12\x08\n\x04Ping\x10\x02\x12\x19\n\x15\x44isconnectUserSession\x10\x04\x12\x15\n\x11LogOffUserSession\x10\x05\x12\x1c\n\x18\x46\x64sApiVirtualChannelOpen\x10\x06\x12\r\n\tLogonUser\x10\x07\x12\x0c\n\x08SwitchTo\x10\x08')

_MSGTYPE = descriptor.EnumDescriptor(
  name='MSGTYPE',
  full_name='freerds.icp.MSGTYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='IsChannelAllowed', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Ping', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DisconnectUserSession', index=2, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LogOffUserSession', index=3, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FdsApiVirtualChannelOpen', index=4, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LogonUser', index=5, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SwitchTo', index=6, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=759,
  serialized_end=909,
)


IsChannelAllowed = 1
Ping = 2
DisconnectUserSession = 4
LogOffUserSession = 5
FdsApiVirtualChannelOpen = 6
LogonUser = 7
SwitchTo = 8



_ISCHANNELALLOWEDREQUEST = descriptor.Descriptor(
  name='IsChannelAllowedRequest',
  full_name='freerds.icp.IsChannelAllowedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ChannelName', full_name='freerds.icp.IsChannelAllowedRequest.ChannelName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=72,
)


_ISCHANNELALLOWEDRESPONSE = descriptor.Descriptor(
  name='IsChannelAllowedResponse',
  full_name='freerds.icp.IsChannelAllowedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ChannelAllowed', full_name='freerds.icp.IsChannelAllowedResponse.ChannelAllowed', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=124,
)


_PINGREQUEST = descriptor.Descriptor(
  name='PingRequest',
  full_name='freerds.icp.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=139,
)


_PINGRESPONSE = descriptor.Descriptor(
  name='PingResponse',
  full_name='freerds.icp.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pong', full_name='freerds.icp.PingResponse.pong', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=141,
  serialized_end=169,
)


_DISCONNECTUSERSESSIONREQUEST = descriptor.Descriptor(
  name='DisconnectUserSessionRequest',
  full_name='freerds.icp.DisconnectUserSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ConnectionId', full_name='freerds.icp.DisconnectUserSessionRequest.ConnectionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=223,
)


_DISCONNECTUSERSESSIONRESPONSE = descriptor.Descriptor(
  name='DisconnectUserSessionResponse',
  full_name='freerds.icp.DisconnectUserSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='disconnected', full_name='freerds.icp.DisconnectUserSessionResponse.disconnected', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=278,
)


_LOGOFFUSERSESSIONREQUEST = descriptor.Descriptor(
  name='LogOffUserSessionRequest',
  full_name='freerds.icp.LogOffUserSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ConnectionId', full_name='freerds.icp.LogOffUserSessionRequest.ConnectionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=280,
  serialized_end=328,
)


_LOGOFFUSERSESSIONRESPONSE = descriptor.Descriptor(
  name='LogOffUserSessionResponse',
  full_name='freerds.icp.LogOffUserSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='loggedoff', full_name='freerds.icp.LogOffUserSessionResponse.loggedoff', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=330,
  serialized_end=376,
)


_FDSAPIVIRTUALCHANNELOPENREQUEST = descriptor.Descriptor(
  name='FdsApiVirtualChannelOpenRequest',
  full_name='freerds.icp.FdsApiVirtualChannelOpenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='SessionID', full_name='freerds.icp.FdsApiVirtualChannelOpenRequest.SessionID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='VirtualName', full_name='freerds.icp.FdsApiVirtualChannelOpenRequest.VirtualName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=378,
  serialized_end=451,
)


_FDSAPIVIRTUALCHANNELOPENRESPONSE = descriptor.Descriptor(
  name='FdsApiVirtualChannelOpenResponse',
  full_name='freerds.icp.FdsApiVirtualChannelOpenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ConnectionString', full_name='freerds.icp.FdsApiVirtualChannelOpenResponse.ConnectionString', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=453,
  serialized_end=513,
)


_LOGONUSERREQUEST = descriptor.Descriptor(
  name='LogonUserRequest',
  full_name='freerds.icp.LogonUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ConnectionId', full_name='freerds.icp.LogonUserRequest.ConnectionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Username', full_name='freerds.icp.LogonUserRequest.Username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Password', full_name='freerds.icp.LogonUserRequest.Password', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Domain', full_name='freerds.icp.LogonUserRequest.Domain', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=515,
  serialized_end=607,
)


_LOGONUSERRESPONSE = descriptor.Descriptor(
  name='LogonUserResponse',
  full_name='freerds.icp.LogonUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ServiceEndpoint', full_name='freerds.icp.LogonUserResponse.ServiceEndpoint', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=609,
  serialized_end=653,
)


_SWITCHTOREQUEST = descriptor.Descriptor(
  name='SwitchToRequest',
  full_name='freerds.icp.SwitchToRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='connectionId', full_name='freerds.icp.SwitchToRequest.connectionId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serviceEndpoint', full_name='freerds.icp.SwitchToRequest.serviceEndpoint', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=655,
  serialized_end=719,
)


_SWITCHTORESPONSE = descriptor.Descriptor(
  name='SwitchToResponse',
  full_name='freerds.icp.SwitchToResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='success', full_name='freerds.icp.SwitchToResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=721,
  serialized_end=756,
)

DESCRIPTOR.message_types_by_name['IsChannelAllowedRequest'] = _ISCHANNELALLOWEDREQUEST
DESCRIPTOR.message_types_by_name['IsChannelAllowedResponse'] = _ISCHANNELALLOWEDRESPONSE
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['DisconnectUserSessionRequest'] = _DISCONNECTUSERSESSIONREQUEST
DESCRIPTOR.message_types_by_name['DisconnectUserSessionResponse'] = _DISCONNECTUSERSESSIONRESPONSE
DESCRIPTOR.message_types_by_name['LogOffUserSessionRequest'] = _LOGOFFUSERSESSIONREQUEST
DESCRIPTOR.message_types_by_name['LogOffUserSessionResponse'] = _LOGOFFUSERSESSIONRESPONSE
DESCRIPTOR.message_types_by_name['FdsApiVirtualChannelOpenRequest'] = _FDSAPIVIRTUALCHANNELOPENREQUEST
DESCRIPTOR.message_types_by_name['FdsApiVirtualChannelOpenResponse'] = _FDSAPIVIRTUALCHANNELOPENRESPONSE
DESCRIPTOR.message_types_by_name['LogonUserRequest'] = _LOGONUSERREQUEST
DESCRIPTOR.message_types_by_name['LogonUserResponse'] = _LOGONUSERRESPONSE
DESCRIPTOR.message_types_by_name['SwitchToRequest'] = _SWITCHTOREQUEST
DESCRIPTOR.message_types_by_name['SwitchToResponse'] = _SWITCHTORESPONSE

class IsChannelAllowedRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ISCHANNELALLOWEDREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.IsChannelAllowedRequest)

class IsChannelAllowedResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ISCHANNELALLOWEDRESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.IsChannelAllowedResponse)

class PingRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.PingRequest)

class PingResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGRESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.PingResponse)

class DisconnectUserSessionRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISCONNECTUSERSESSIONREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.DisconnectUserSessionRequest)

class DisconnectUserSessionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISCONNECTUSERSESSIONRESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.DisconnectUserSessionResponse)

class LogOffUserSessionRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGOFFUSERSESSIONREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.LogOffUserSessionRequest)

class LogOffUserSessionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGOFFUSERSESSIONRESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.LogOffUserSessionResponse)

class FdsApiVirtualChannelOpenRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FDSAPIVIRTUALCHANNELOPENREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.FdsApiVirtualChannelOpenRequest)

class FdsApiVirtualChannelOpenResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FDSAPIVIRTUALCHANNELOPENRESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.FdsApiVirtualChannelOpenResponse)

class LogonUserRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGONUSERREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.LogonUserRequest)

class LogonUserResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGONUSERRESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.LogonUserResponse)

class SwitchToRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SWITCHTOREQUEST
  
  # @@protoc_insertion_point(class_scope:freerds.icp.SwitchToRequest)

class SwitchToResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SWITCHTORESPONSE
  
  # @@protoc_insertion_point(class_scope:freerds.icp.SwitchToResponse)

# @@protoc_insertion_point(module_scope)
